name: Test compose

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - uses: adambirds/docker-compose-action@v1.3.0
      with:
        compose-file: "docker-compose.yml"
        test-container: passbolt
        test-command: "su  -c \"/usr/share/php/passbolt/bin/cake passbolt register_user  -u your@email.com -f yourname -l surname  -r admin\" www-data"
